### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by ProgrammerFB** [DMXControl/ArtNetSharp#4]
Hi,

I'm writing software to run an artnet node and I did it on Windows, but i need to run it on Debian based Linux. I compiled the program for linux-arm64 in VS, but the ArtNet part doesn't work.

**Comment by patrick-dmxc** [comment]
How you check its not working?

**Comment by patrick-dmxc** [comment]
With this are to less informatio, Use Whiershark for investigation.
With the information "Its not working", i cant help you

**Comment by ProgrammerFB** [comment]
In wireshark you can see all the packets.

![screenshot1](https://github.com/DMXControl/ArtNetSharp/assets/165289513/dc7662c1-7394-42b0-9c27-06a4305e7a60)

I know qlc+ isn't entirely consistent with the artnet4, but it's easy and fast to use, and program based on your library can work with that.

I'm running the same app based on ArtNetSharp on windows and on linux.

On windows i'm reciving packets (I'm printing only part of data):
![image](https://github.com/DMXControl/ArtNetSharp/assets/165289513/79090ed7-f22e-4f90-a717-6df557a93bd4)

On Linux the same program doesn't enter into artnet recive event (I checked it in the debugger):
![image](https://github.com/DMXControl/ArtNetSharp/assets/165289513/17cfb836-256d-4a98-bf7f-ca7a5c13f1df)

**Comment by patrick-dmxc** [comment]
Ok, how does Wireshark look like on linux?

**Comment by ProgrammerFB** [comment]
Same

![image](https://github.com/DMXControl/ArtNetSharp/assets/165289513/499212df-3339-4358-8eb8-62fe0fbf1f0a)

**Comment by patrick-dmxc** [comment]
Try again with this version
https://github.com/DMXControl/ArtNetSharp/releases/tag/v0.0.15
I prefere to use nuget to be always up to date

**Comment by patrick-dmxc** [comment]
If its not Working, send me the logs,
They should be somewhere like"/home/<Appdata>/ArtNetSharp/log.txt"

**Comment by ProgrammerFB** [comment]
Here is first log from linux:

05/04/2024 09:42:15 [Trace] <ArtNet> Initialized!
05/04/2024 09:42:15 [Trace] <ArtNet> Client (10.0.0.255) Cleared
05/04/2024 09:42:15 [Debug] <ArtNet> Added NetworkClient 10.0.0.255
05/04/2024 09:42:15 [Debug] <ArtNet> 
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 105
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient()
   at ArtNetSharp.ArtNet.NetworkClientBag..ctor(IPAddress broadcastIpAddress) in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 73
   at ArtNetSharp.ArtNet.updateNetworkClients() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 269
   at ArtNetSharp.ArtNet..ctor() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 244
   at ArtNetSharp.ArtNet.get_Instance() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 25
   at ArtNetSharp.Communication.AbstractInstance..ctor() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\Communication\AbstractInstance.cs:line 180
   at ArtNetSharp.Communication.NodeInstance..ctor()
   at ArtNetDriver.ArtNet_Driver..ctor(UInt16 universe, OnEventDMXDelegate onEventDMX, String name) in E:\Prace_biezace\ArtNet\ArtNet_Testy\ArtNet_Testy\ArtNet_Driver.cs:line 19
   at Testy.Program.Main(String[] args) in E:\Prace_biezace\ArtNet\ArtNet_Testy\ArtNet_Testy\Program.cs:line 15
--- End of stack trace from previous location ---
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 105
05/04/2024 09:42:17 [Debug] <ArtNet> Removed instance 
05/04/2024 09:42:17 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
05/04/2024 09:42:17 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
05/04/2024 09:42:20 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:42:21 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:42:21 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
05/04/2024 09:42:21 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
05/04/2024 09:42:21 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:42:22 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:42:23 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:42:23 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
05/04/2024 09:42:23 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
05/04/2024 09:42:25 [Debug] <ArtNet> Removed instance B+R RPI


And the second one from Linux to be sure:

05/04/2024 09:47:05 [Trace] <ArtNet> Initialized!
05/04/2024 09:47:05 [Trace] <ArtNet> Client (10.0.0.255) Cleared
05/04/2024 09:47:05 [Debug] <ArtNet> Added NetworkClient 10.0.0.255
05/04/2024 09:47:05 [Debug] <ArtNet> 
System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 105
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient()
   at ArtNetSharp.ArtNet.NetworkClientBag..ctor(IPAddress broadcastIpAddress) in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 73
   at ArtNetSharp.ArtNet.updateNetworkClients() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 269
   at ArtNetSharp.ArtNet..ctor() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 244
   at ArtNetSharp.ArtNet.get_Instance() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 25
   at ArtNetSharp.Communication.AbstractInstance..ctor() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\Communication\AbstractInstance.cs:line 180
   at ArtNetSharp.Communication.NodeInstance..ctor()
   at ArtNetDriver.ArtNet_Driver..ctor(UInt16 universe, OnEventDMXDelegate onEventDMX, String name) in E:\Prace_biezace\ArtNet\ArtNet_Testy\ArtNet_Testy\ArtNet_Driver.cs:line 19
   at Testy.Program.Main(String[] args) in E:\Prace_biezace\ArtNet\ArtNet_Testy\ArtNet_Testy\Program.cs:line 15
--- End of stack trace from previous location ---
   at ArtNetSharp.ArtNet.NetworkClientBag.openClient() in E:\Prace_biezace\ArtNetSharp-0.0.15\ArtNetSharp\ArtNet.cs:line 105
05/04/2024 09:47:19 [Debug] <ArtNet> Removed instance 
05/04/2024 09:47:19 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
05/04/2024 09:47:19 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
05/04/2024 09:47:19 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:47:20 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:47:26 [Debug] <ArtNet> Removed instance B+R RPI
05/04/2024 09:47:26 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
05/04/2024 09:47:26 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
05/04/2024 09:47:27 [Debug] <ArtNet> Removed instance B+R RPI


In both logs is problem with permission. I tried run this app as a root but it doesn't help. I was looking for log from app root run but i can't find it.

**Comment by patrick-dmxc** [comment]
Try again with
[https://github.com/DMXControl/ArtNetSharp/releases/tag/v0.0.16](v0.0.16)

If its not working please post the logs again

**Comment by ProgrammerFB** [comment]
Exception disappeared, but still I can't recive packets. In wireshark I see packets, but I can't catch them with ArtNetSharp. I added more node instances to make it easier to detect any packet. When qlc+ on RPI is running, app based on ArtNetSharp is generating logs like this:

_08/04/2024 06:19:30 [Trace] <ArtNet> Initialized!
08/04/2024 06:19:30 [Trace] <ArtNet> Client (10.0.0.255) Cleared
08/04/2024 06:19:30 [Trace] <ArtNet> Client (10.0.0.233) Initialized
08/04/2024 06:19:30 [Debug] <ArtNet> Added NetworkClient 10.0.0.255
08/04/2024 06:19:31 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:31 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:33 [Debug] <ArtNet> Removed instance 
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 1
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 6
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 7
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 8
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 9
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 10
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 11
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 12
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 13
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 14
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 15
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 16
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 17
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 18
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 19
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 20
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 21
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 22
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 23
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 24
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 25
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 26
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 27
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 28
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 29
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 30
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 31
08/04/2024 06:19:33 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 3
08/04/2024 06:19:33 [Debug] <NodeInstance> Added instance PortConfig: Output Port 4
08/04/2024 06:19:36 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:36 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:37 [Information] <NodeInstance> Discovered: D0:50:99:08:CB:54#0#65535#65535
08/04/2024 06:19:38 [Information] <NodeInstance> Discovered: 70:85:C2:89:AA:79#0#65535#65535
08/04/2024 06:19:41 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:41 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:46 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:46 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:51 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:51 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:56 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:56 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:19:59 [Debug] <ArtNet> Removed instance B+R RPI
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 1
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 3
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 4
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 6
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 7
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 8
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 9
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 10
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 11
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 12
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 13
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 14
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 15
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 17
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 16
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 18
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 19
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 20
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 21
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 22
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 23
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 24
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 25
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 26
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 27
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 28
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 29
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 30
08/04/2024 06:19:59 [Debug] <NodeInstance> Added instance PortConfig: Output Port 31
08/04/2024 06:19:59 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
08/04/2024 06:20:01 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:01 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:06 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:06 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:08 [Debug] <ArtNet> Removed instance B+R RPI
08/04/2024 06:20:11 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:11 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:14 [Debug] <ArtNet> Removed instance B+R RPI
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 3
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 4
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 1
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 6
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 7
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 9
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 10
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 11
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 13
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 12
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 15
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 14
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 16
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 17
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 18
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 19
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 20
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 21
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 22
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 23
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 24
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 25
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 26
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 27
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 28
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 29
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 30
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 8
08/04/2024 06:20:14 [Debug] <NodeInstance> Added instance PortConfig: Output Port 31
08/04/2024 06:20:14 [Debug] <ArtNet> Added instance NodeInstance: PI (PI)
08/04/2024 06:20:16 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:16 [Information] <NodeInstance> Timeout: 70:85:C2:89:AA:79#0#65535#65535
08/04/2024 06:20:16 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:17 [Information] <NodeInstance> Discovered: 70:85:C2:89:AA:79#0#65535#65535
08/04/2024 06:20:21 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:21 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:26 [Trace] <ArtNet> Received Packet from 10.0.0.228 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff
08/04/2024 06:20:26 [Trace] <ArtNet> Received Packet from 10.0.0.165 -> ArtPollReply: Q Light Controller Plus - ArtNet interface - #0 OEM:ffff, Manuf.:ffff_



When qlc+ is disabled(but on widnows is still enabled), ArtNetSharp can't see anything:



_08/04/2024 06:31:21 [Trace] <ArtNet> Initialized!
08/04/2024 06:31:21 [Trace] <ArtNet> Client (10.0.0.255) Cleared
08/04/2024 06:31:21 [Trace] <ArtNet> Client (10.0.0.233) Initialized
08/04/2024 06:31:21 [Debug] <ArtNet> Added NetworkClient 10.0.0.255
08/04/2024 06:31:29 [Debug] <ArtNet> Removed instance 
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 1
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 3
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 4
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 6
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 7
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 8
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 9
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 10
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 11
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 12
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 13
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 14
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 15
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 16
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 17
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 18
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 19
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 20
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 21
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 22
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 23
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 24
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 25
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 26
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 27
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 28
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 29
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 30
08/04/2024 06:31:29 [Debug] <NodeInstance> Added instance PortConfig: Output Port 31
08/04/2024 06:31:29 [Debug] <ArtNet> Added instance NodeInstance: B+R RPI (B+R RPI)
08/04/2024 06:31:54 [Debug] <ArtNet> Removed instance B+R RPI
08/04/2024 06:31:56 [Debug] <ArtNet> Removed instance B+R RPI
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 0
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 2
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 3
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 4
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 5
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 6
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 7
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 8
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 9
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 10
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 11
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 12
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 13
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 14
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 15
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 16
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 17
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 18
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 19
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 20
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 21
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 22
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 23
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 24
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 25
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 26
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 27
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 28
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 29
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 30
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 31
08/04/2024 06:31:56 [Debug] <ArtNet> Added instance NodeInstance: PI (PI)
08/04/2024 06:31:56 [Debug] <NodeInstance> Added instance PortConfig: Output Port 1
08/04/2024 06:32:12 [Debug] <ArtNet> Removed instance PI_

**Comment by ProgrammerFB** [comment]
Do you think you will find a solution in the near future? I need an ArtNet implementation and your library looks good but doesn't doesn't quite work on my 64-bit Raspbian

**Comment by patrick-dmxc** [comment]
I dont have a working test-environment for Linux, So investigation is difficult,
Maybe a colegue can help

**Comment by ProgrammerFB** [comment]
Works as it should! Thank you for your help, now I can continue project
